### ISSUE TITLE
core-estimator works on my development server, but not on my web page

### ISSUE THREAD

**Issue by DanielLangdon** [oftn/core-estimator#7]
I recently had to reinstall Windows on my computer.  I freshly installed all major browsers.  You may recall that I use core-estimator on my web page at http://danielsadventure.info/html5fractal/.

This page seems to work fine with IE and Chrome (altho IE tends to misestimate the number of cores), but for some reason, Firefox hangs when trying to estimate the number of cores.

The strange thing is that this happens only in Firefox and only when I run the page on my public web server.  When I run it in the Visual Studio development server, it works fine.  Furthermore, Firefox shows no error indicating that anything went wrong, and the browser itself does not hang; only the Javascript seems to stop.

**Comment by eligrey** [comment]
Seeing as the behavior is different off your dev server, it may be partly caching-related. Please clear your entire cache in Firefox and report back.

As for the general JS hang, I will look into Core Estimator on the current version of Firefox later today.

**Comment by DanielLangdon** [comment]
As this happened with a fresh installation of Windows 8 and Firefox, I don't see how caching could be a problem.  I did go ahead and clear my cache several times, but the behavior is frustratingly persistent.

The issue only happens with Firefox and only when the page runs on the public web server, as opposed to the development server.  When you access the page for the first time, it immediately invokes core-estimator, so it should be easy for you to reproduce the problem: just point your browser here: http://danielsadventure.info/html5fractal/.

If you don't see the same issue and you're using the latest version of Firefox, that would suggest that there is a problem with my setup, but as of now, I have no idea what is causing the problem.

**Comment by eligrey** [comment]
Yeah, the estimator is definitely freezing for me on Firefox as well (the page itself is still responsive though). I'll help look into this later today.

**Comment by DanielLangdon** [comment]
Thanks, Eli.  I can understand Chrome working, but not Firefox due to Chrome using the NaCl system, but one would think that if it works in IE, it should work in Firefox because both are doing some heavy number crunching to estimate performance the same way.

**Comment by eligrey** [comment]
Yeah, it may actually be a bug in Firefox. Hopefully it's not and is something I can fix in Core Estimator.

**Comment by eligrey** [comment]
I spent a few minutes tonight checking it out but it isn't very obvious. I'll look more tomorrow.

**Comment by DanielLangdon** [comment]
Eli, I spent some more time poking at this.

I reduced the complex web page down to the bare bones required to reproduce the problem and published this to http://danielsadventure.info/test.

There are only four lines of code in addition to your .js files.  Maybe this will make it easier for you to help me fix it.

**Comment by eligrey** [comment]
Checking out your reduced testcase now. I'll see what I can find.

**Comment by eligrey** [comment]
I'm really sorry, but I can't seem to reproduce your problem anymore in Firefox on the reduced testcase or even on http://danielsadventure.info/html5fractal/, as I'm getting the alert with the # of cores result now. I ran it a bunch of times to see if the issue would come up but it won't.

I updated Firefox yesterday. Are you encountering this issue on Firefox 38.0.1?

**Comment by DanielLangdon** [comment]
Hmmmm.... I wonder what is causing this.  I forgot to tell you earlier that it seems to reproduce about 9 times out of 10 on http://danielsadventure.info/test, but I have no idea why... perhaps some sort of race condition or something.  For what it's worth, if I open up the "Task Manager" and reproduce the problem, I see the CPU usage spike for a second or so and then drop back down close to 0 as the page hangs.

I recently upgraded to a 4-core 4 GHz i7 machine, so maybe the hardware has something to do with it.  Your test page (http://wg.oftn.org/projects/core-estimator/demo/) seems to work fine every time.

Maybe you can point me to directions for using your version of the core estimator with feedback that shows the numbers lighting up as it guesses at the number of cores?  Perhaps that would shed some light on the situation.

**Comment by DanielLangdon** [comment]
Oh, and yes, my Firefox version is 38.0.1

**Comment by eligrey** [comment]
I'm sorry that I'm no help finding this possible race condition so far. I may cross-post this to a programming group IRC channel I frequent or to StackOverflow if a it doesn't look like we can find the solution soon.

**Comment by DanielLangdon** [comment]
Okey, dokey... I just tried to reproduce this again with Firefox 38.0.5.  It works fine now, so it seems that there is some issue with that particular version of Firefox I was using before: 38.0.1
